/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.util.List;
import mundial.Estadio;
import mundial.Main;

/**
 *
 * @author Carla Daniela
 */
public class ESTADIOS extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public ESTADIOS() {
        initComponents();
        this.setLocationRelativeTo(null);               

        List<Estadio> estadios = Main.listaEstadios;
    
        StringBuilder estadioList = new StringBuilder();
        for (Estadio estadio : estadios) {
            estadioList.append(estadio.mostrarInfo()).append("\n");
        }
        lista.setText(estadioList.toString());

        // Show the JScrollPane containing the JTextArea
        lista.setEditable(false); 
        lista.setVisible(true);                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AREAESTADIO = new javax.swing.JScrollPane();
        lista = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        SALIR = new javax.swing.JToggleButton();
        ESTADIO = new javax.swing.JToggleButton();
        PARTIDO = new javax.swing.JToggleButton();
        JUGADORES = new javax.swing.JToggleButton();
        CREAR = new javax.swing.JToggleButton();
        BARRA = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lista.setColumns(20);
        lista.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lista.setRows(5);
        AREAESTADIO.setViewportView(lista);

        getContentPane().add(AREAESTADIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 550, 450));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setText(" MENÚ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 80, 30));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, 30));

        SALIR.setBackground(new java.awt.Color(255, 102, 102));
        SALIR.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        SALIR.setForeground(new java.awt.Color(255, 255, 255));
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 160, 40));

        ESTADIO.setBackground(new java.awt.Color(102, 153, 255));
        ESTADIO.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        ESTADIO.setForeground(new java.awt.Color(255, 255, 255));
        ESTADIO.setText("ESTADIOS");
        ESTADIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESTADIOActionPerformed(evt);
            }
        });
        getContentPane().add(ESTADIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 160, 40));

        PARTIDO.setBackground(new java.awt.Color(102, 153, 255));
        PARTIDO.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        PARTIDO.setForeground(new java.awt.Color(255, 255, 255));
        PARTIDO.setText("PARTIDOS");
        PARTIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PARTIDOActionPerformed(evt);
            }
        });
        getContentPane().add(PARTIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, 40));

        JUGADORES.setBackground(new java.awt.Color(102, 153, 255));
        JUGADORES.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        JUGADORES.setForeground(new java.awt.Color(255, 255, 255));
        JUGADORES.setText("JUGADORES");
        JUGADORES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUGADORESActionPerformed(evt);
            }
        });
        getContentPane().add(JUGADORES, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 40));

        CREAR.setBackground(new java.awt.Color(102, 153, 255));
        CREAR.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        CREAR.setForeground(new java.awt.Color(255, 255, 255));
        CREAR.setText("CREAR EQUIPOS");
        CREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREARActionPerformed(evt);
            }
        });
        getContentPane().add(CREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, 40));

        BARRA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/barra_mundial (1).png"))); // NOI18N
        BARRA.setText("jLabel2");
        getContentPane().add(BARRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 480));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_mundial.png"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREARActionPerformed
        new EQUIPOS().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CREARActionPerformed

    private void JUGADORESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUGADORESActionPerformed
        new JUGADORES().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JUGADORESActionPerformed

    private void PARTIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PARTIDOActionPerformed
        new JUGAR().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PARTIDOActionPerformed

    private void ESTADIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESTADIOActionPerformed

    }//GEN-LAST:event_ESTADIOActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ESTADIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ESTADIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ESTADIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ESTADIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ESTADIOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane AREAESTADIO;
    private javax.swing.JLabel BARRA;
    private javax.swing.JToggleButton CREAR;
    private javax.swing.JToggleButton ESTADIO;
    private javax.swing.JLabel FONDO;
    private javax.swing.JToggleButton JUGADORES;
    private javax.swing.JToggleButton PARTIDO;
    private javax.swing.JToggleButton SALIR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea lista;
    // End of variables declaration//GEN-END:variables
}
