/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.util.List;
import javax.swing.JOptionPane;
import mundial.Equipo;
import mundial.Estadio;
import mundial.Main;
import static mundial.Main.listaEquipos;
import mundial.Partido;

/**
 *
 * @author Carla Daniela
 */
public class JUGAR extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public JUGAR() {
        initComponents();
        this.setLocationRelativeTo(null);                             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JUEGUEN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EQUIPO2 = new javax.swing.JTextField();
        EQUIPO1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        SALIR = new javax.swing.JToggleButton();
        ESTADIO = new javax.swing.JToggleButton();
        PARTIDO = new javax.swing.JToggleButton();
        JUGADORES = new javax.swing.JToggleButton();
        CREAR = new javax.swing.JToggleButton();
        BARRA = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JUEGUEN.setBackground(new java.awt.Color(255, 102, 102));
        JUEGUEN.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        JUEGUEN.setForeground(new java.awt.Color(255, 255, 255));
        JUEGUEN.setText("JUEGUEN");
        JUEGUEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUEGUENActionPerformed(evt);
            }
        });
        getContentPane().add(JUEGUEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 180, 40));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel4.setText(" EQUIPO 01:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 150, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel3.setText("  EQUIPO 02:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 150, 30));

        EQUIPO2.setBackground(new java.awt.Color(204, 204, 255));
        EQUIPO2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        getContentPane().add(EQUIPO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 200, -1));

        EQUIPO1.setBackground(new java.awt.Color(204, 204, 255));
        EQUIPO1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        getContentPane().add(EQUIPO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 200, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setText(" MENÚ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 80, 30));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, 30));

        SALIR.setBackground(new java.awt.Color(255, 102, 102));
        SALIR.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        SALIR.setForeground(new java.awt.Color(255, 255, 255));
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 160, 40));

        ESTADIO.setBackground(new java.awt.Color(102, 153, 255));
        ESTADIO.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        ESTADIO.setForeground(new java.awt.Color(255, 255, 255));
        ESTADIO.setText("ESTADIOS");
        ESTADIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESTADIOActionPerformed(evt);
            }
        });
        getContentPane().add(ESTADIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 160, 40));

        PARTIDO.setBackground(new java.awt.Color(102, 153, 255));
        PARTIDO.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        PARTIDO.setForeground(new java.awt.Color(255, 255, 255));
        PARTIDO.setText("PARTIDOS");
        PARTIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PARTIDOActionPerformed(evt);
            }
        });
        getContentPane().add(PARTIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, 40));

        JUGADORES.setBackground(new java.awt.Color(102, 153, 255));
        JUGADORES.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        JUGADORES.setForeground(new java.awt.Color(255, 255, 255));
        JUGADORES.setText("JUGADORES");
        JUGADORES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUGADORESActionPerformed(evt);
            }
        });
        getContentPane().add(JUGADORES, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 160, 40));

        CREAR.setBackground(new java.awt.Color(102, 153, 255));
        CREAR.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        CREAR.setForeground(new java.awt.Color(255, 255, 255));
        CREAR.setText("CREAR EQUIPOS");
        CREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREARActionPerformed(evt);
            }
        });
        getContentPane().add(CREAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 160, 40));

        BARRA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/barra_mundial (1).png"))); // NOI18N
        BARRA.setText("jLabel2");
        getContentPane().add(BARRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 480));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_mundial.png"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREARActionPerformed
        new EQUIPOS().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CREARActionPerformed

    private void JUGADORESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUGADORESActionPerformed
        new JUGADORES().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JUGADORESActionPerformed

    private void PARTIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PARTIDOActionPerformed
        new JUGAR().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PARTIDOActionPerformed

    private void ESTADIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESTADIOActionPerformed

    }//GEN-LAST:event_ESTADIOActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JUEGUENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUEGUENActionPerformed
    // Obtener el nombre del equipo 1 y 2 desde el campo EQUIPO1
    String equipo1 = EQUIPO1.getText().trim();
    String equipo2 = EQUIPO2.getText().trim();    
    // Verificar si el nombre del equipo 1 está en la lista de equipos
    boolean equipoEncontrado = false;
    Equipo equipoSeleccionado = null;
    for (Equipo equipo : Main.listaEquipos) {
    if (equipo.getNombre().equalsIgnoreCase(equipo1)) {
        equipoEncontrado = true;
        equipoSeleccionado = equipo;
        break;
    }
    }
    
        if (!equipoEncontrado) {
        JOptionPane.showMessageDialog(this, "El nombre del EQUIPO 02 no es válido", "Error", JOptionPane.ERROR_MESSAGE);
        }
    // Verificar si el nombre del equipo 2 está en la lista de equipos y es diferente al equipo 1
    boolean equipo2Encontrado = false;
    Equipo equipo2Seleccionado = null;
    for (Equipo equipo : Main.listaEquipos) {
    if (equipo.getNombre().equalsIgnoreCase(equipo2)) {
        equipo2Encontrado = true;
        break;
    }
}
    if (!equipo2Encontrado) {
    JOptionPane.showMessageDialog(this, "El nombre del EQUIPO 02 no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Verificar si equipo2 es igual a equipo1
if (equipo2.equalsIgnoreCase(equipo1)) {
    JOptionPane.showMessageDialog(this, "El EQUIPO 02 no puede ser igual al EQUIPO 01.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}
    
    // Si ambos equipos son válidos y diferentes, ejecutar el método jugarPartido()
    Partido.jugarPartido();

    String resultado = Partido.mostrarResultado(); // Suponiendo que mostrarResultado() devuelve el resultado como un String

// Mostrar el resultado en un mensaje de texto
    JOptionPane.showMessageDialog(this, "Resultado del partido:\n" + resultado, "Resultado del Partido", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_JUEGUENActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JUGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JUGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JUGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JUGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JUGAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BARRA;
    private javax.swing.JToggleButton CREAR;
    private javax.swing.JTextField EQUIPO1;
    private javax.swing.JTextField EQUIPO2;
    private javax.swing.JToggleButton ESTADIO;
    private javax.swing.JLabel FONDO;
    private javax.swing.JButton JUEGUEN;
    private javax.swing.JToggleButton JUGADORES;
    private javax.swing.JToggleButton PARTIDO;
    private javax.swing.JToggleButton SALIR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
